### ISSUE TITLE
Reading from any network library with stream=True produces errors

### ISSUE THREAD

**Issue by comonadd** [daggaz/json-stream#57]
I am trying to read 
```python
import json_stream
import json_stream.requests
import requests


def read_data():
    url = "http://127.0.0.1:4000/big_data.json"
    headers = {}
    with requests.get(url=url, headers=headers, stream=True, timeout=20000) as response:
        iter = json_stream.requests.load(response)
        return iter


iterator = read_data()
for item in iterator:
    print(item)
```

But it throws this:
```
4010
Traceback (most recent call last):
  File "/Users/comonadd/Documents/testing-json-streaming/main.py", line 15, in <module>
    for item in iterator:
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 229, in <genexpr>
    return (k for k, v in self._iter_items())
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 48, in _iter_items
    self._clear_child()
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 41, in _clear_child
    self._child.read_all()
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 62, in read_all
    collections.deque(self._iter_items(), maxlen=0)
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 48, in _iter_items
    self._clear_child()
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 41, in _clear_child
    self._child.read_all()
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 62, in read_all
    collections.deque(self._iter_items(), maxlen=0)
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 48, in _iter_items
    self._clear_child()
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 41, in _clear_child
    self._child.read_all()
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 62, in read_all
    collections.deque(self._iter_items(), maxlen=0)
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 48, in _iter_items
    self._clear_child()
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 41, in _clear_child
    self._child.read_all()
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 62, in read_all
    collections.deque(self._iter_items(), maxlen=0)
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 50, in _iter_items
    item = self._load_item()
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 215, in _load_item
    token_type, k = next(self._stream)
ValueError: Unterminated string at end of file at index 10240
```

I have tried using httpx, requests, and urlllib, and all of them throw similar messages. What am I doing wrong here?

**Comment by comonadd** [comment]
Ok, so the problem here was that `with` context was lost and stream is closed, which is why the library couldn't read any further. Just parse inside of `with` context.

**Comment by daggaz** [comment]
Hey,

If you just load the raw resource, and see what is at/around the index it's complaining about?

Can you supply the original file, or a minimal example that triggers the error?

Jamie

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Dmitry Guzeev ***@***.***>
Sent: Monday, March 11, 2024 12:09:30 PM
To: daggaz/json-stream ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [daggaz/json-stream] Reading from any network library with stream=True produces errors (Issue #57)


I am trying to read

import json_stream
import json_stream.requests
import requests


def read_data():
    url = "http://127.0.0.1:4000/big_data.json"
    headers = {}
    with requests.get(url=url, headers=headers, stream=True, timeout=20000) as response:
        iter = json_stream.requests.load(response)
        return iter


iterator = read_data()
for item in iterator:
    print(item)

But it throws this:

4010
Traceback (most recent call last):
  File "/Users/comonadd/Documents/testing-json-streaming/main.py", line 15, in <module>
    for item in iterator:
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 229, in <genexpr>
    return (k for k, v in self._iter_items())
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 48, in _iter_items
    self._clear_child()
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 41, in _clear_child
    self._child.read_all()
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 62, in read_all
    collections.deque(self._iter_items(), maxlen=0)
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 48, in _iter_items
    self._clear_child()
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 41, in _clear_child
    self._child.read_all()
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 62, in read_all
    collections.deque(self._iter_items(), maxlen=0)
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 48, in _iter_items
    self._clear_child()
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 41, in _clear_child
    self._child.read_all()
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 62, in read_all
    collections.deque(self._iter_items(), maxlen=0)
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 48, in _iter_items
    self._clear_child()
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 41, in _clear_child
    self._child.read_all()
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 62, in read_all
    collections.deque(self._iter_items(), maxlen=0)
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 50, in _iter_items
    item = self._load_item()
  File "/Users/comonadd/Library/Python/3.9/lib/python/site-packages/json_stream/base.py", line 215, in _load_item
    token_type, k = next(self._stream)
ValueError: Unterminated string at end of file at index 10240


I have tried using httpx, requests, and urlllib, and all of them throw similar messages. What am I doing wrong here?
